### PR TITLE
Upgrading to sidekiq 3.2

### PR DESCRIPTION
**Pull request by agirorn**

### CODE REVIEW

**Comment by tiredpixel** [comment]
@agirorn, hello! Thank you for this pull request. :)

As you can hopefully see from the section above, unfortunately the (Travis) CI build for this branch failed. The stacktrace reports that

```
Sidekiq 3.2.5 does not support Ruby 1.9. (RuntimeError)
```

This is tricksy, however, as sidekiq-spy still supports Ruby 1.9.3, as it hasn't yet reached end of life within core. I'm curious about hearing more about this change, if that's alright with you; what problems did you face—was it something in particular in sidekiq-spy which didn't work, or was there an issue locking the `Gemfile`?

I'd also be hesitant about the current lock specification; I think `~> 3.2` forces everyone to upgrade (which might not be desirable or possible for some users). Is it only the extra require which is needed to make sidekiq-spy work with the latest sidekiq, do you think? Would such a require be possible even on 2.x, allowing us to relax the lock specification?

(Very much as an aside, it seems the text editor is stripping spaces throughout the whole file edited, making the commit look like it touches far more than it actually does. Perhaps an auto-strip whitespace configuration option is somehow enabled?)

I'd be interested in hearing your thoughts, particularly if you might know of a solution regarding Ruby 1.9.3. :)

Peace,
tiredpixel

**Comment by agirorn** [comment]
The reason I wanted this is so I can bundle sidekiq-spy my project that is using Sidekiq 3.2.
To get sidekiq-spy working for sidekiq 3.2 we need the require statement and that should work for most version or could be worked around.

Regarding ruby 1.9.3 I think the travis tests just need to be configured some more. For example add a more complicated matrix: like sinatra dose: https://github.com/sinatra/sinatra/blob/master/.travis.yml

``` yaml
matrix:
  include:
    - { rvm: 1.9.3, env: sidekiq=2.17  }
    - { rvm: 2.0.0, env: sidekiq=2.17 }
    - { rvm: 2.0.0, env: sidekiq=3.2 }
    - { rvm: 2.1.0, env: sidekiq=2.17 }
    - { rvm: 2.1.0, env: sidekiq=3.2 }
    - { rvm: 2.1.2, env: sidekiq=2.17 }
    - { rvm: 2.1.2, env: sidekiq=3.2 }
```

Maybe the gemspec should only refer to sidekiq and not the version. That should give the user the final control on which version of sidekiq to use

``` ruby
  spec.add_dependency "sidekiq"
```

yes your right on the money, I do have white space space phobia and my editor helps me. If you dont like it I can clean it up.

**Comment by tiredpixel** [comment]
@agirorn, ah, I see what you mean. I've had a look into the extra require, and it seems okay with any version of sidekiq which actually works for sidekiq-spy (that is, it doesn't seem to decrease support for any version). So, I think we're okay to add it.

With regards to the `gemspec`, I'm also mindful of those using sidekiq-spy outside of a `Gemfile` context, as a standalone. For that, I'd ideally like to force the selection of compatible libraries. Admittedly, the locking currently present isn't as restrictive as it could be, for that. But sidekiq-spy certainly doesn't work with sidekiq 1.x—indeed, I think the earliest that can reasonably be supported is likely sidekiq 2.7.0. This at least boots on ruby 2.1.2—although I haven't tested other versions. So, I think `gemspec`-wise, we could do something like `sidekiq >= 2.7.0`. Would that work for you?

We would also then need to get Travis building, updating the build matrix as you suggested.

Is this something you'd like to do? :) If not, I can branch sidekiq-spy to receive your pull request, then make the extra changes, if that's easier for you. Otherwise, for this pull request I'd be looking for Travis passing with the changes discussed.

With regards to whitespace, I can appreciate your feelings about it; I have feelings about it, too, but unfortunately currently leaning in a different direction to yours. :) With regards to style, I don't mind which people prefer, so long as sections not related to the commit aren't changed. That is, I'd not really blink with a changed method with the containing and surrounding whitespace stripped, but changes throughout the entire file make me a little uncomfortable, I'm afraid. My main reasons for such are the commit history showing changes in that file which aren't the focus of the work, and also making it more likely for merge conflicts if anyone's branched. I hope you can understand. (Perhaps it would be simpler if I just converted to stripping all whitespace myself, but I'm afraid I'm not there, currently. :) )

Thanks again for your work on this!

Peace,
tiredpixel

**Comment by agirorn** [comment]
I have not had any time to follow this through and I'm not using sidekiq at the moment so Iðm closing this pull request.

**Pull request closed without merging**
